### ISSUE TITLE
Help wanted - NAV integration

### ISSUE THREAD

**Issue by pavisalavisa** [vanvoice/nav-hungary-invoice-xml#1]
Hello @fulopattila122 and @kedves,

I'm currently implementing a connection with NAV and I came across this repo.

I'm looking for local experts who have previous experience in building this particular connection.

Would you be interested in providing guidance with the implementation?

**Comment by fulopattila122** [comment]
Hi Antonio. We have abandoned the project which this open-source library was part of, it never went live.
So (un)fortunately we have not become experts within this area.

**Comment by fulopattila122** [comment]
Some help:

- The definitions from the Hungarian Tax Authority (NAV): https://github.com/nav-gov-hu/Online-Invoice
- This lib is maintained and is apparently very up-to-date: https://github.com/pzs/nav-online-invoice The doc is Hungarian, but the code is English

I hope it helps. If you still think we might help, feel free to ping :wink:

**Comment by pavisalavisa** [comment]
Thank you for your quick response.

I've already seen these and I was hoping to find someone who about potential pitfalls and quirks of the system :)

Cheers!

**Comment by fulopattila122** [comment]
> about potential pitfalls and quirks of the system

Apparently there are many :sweat: 
It's way the hottest topic on prog.hu forum:
![image](https://user-images.githubusercontent.com/1162360/108857280-3876b480-75eb-11eb-8c15-aa341fe67e20.png)
